### ISSUE TITLE
Product Import does not allow the usage of image label and  image dimensions 

### ISSUE THREAD

**Issue by skyriakou** [sphereio/sphere-node-product-csv-sync#266]
### Support reference number
https://jira.commercetools.com/browse/SUPPORT-5263

### Description
When an export of products is performed and images are using labels, it is exported like this:

https://jeanscentre-static.joggroup.net/sys-master/images/ha9/hf0/9027232661534/8718212587913_1_W480xH640|ProductImage

url|label;url2|label and so on...

However, to import the same field using sphere-node-product-csv-sync is not possible as the label is not read properly and the image is then imported wrongly.

So, in order to have consistency in export and import products, shouldn't the image field in the import also recognize labels ?

### Expected Behavior
Image field in the import should also recognize labels

### Current Behavior
Importing the same field using sphere-node-product-csv-sync is not possible as the label is not read properly and the image is then imported wrongly.

**Comment by briantomkins** [comment]
Should include images.dimensions h and w when this is fixed.

**Comment by VineetKumarKushwaha** [comment]
There are two issues here :- 
**1) Image Label:-**
When we export products, we are not doing anything with Image Label, we just use the image url.
So When we Import and even though user has added label in the url via sperator, it is not used by us.

Solution:- 
Lets add Label at the end of the of the Image like http://imageurl | **ImageLabel** 

This will be used by import and export both.

**2) Image dimensions:-**
We are not using image dimension in the export and because of that it is not supported in import as well.
Solution:-
Let use this as well in the image url like
 http://imageurl | **ImageLabel** | **400x400** ; http://imageurl | **SecondLabel** |**300x300**

Format:- WxH

So By this we can say last separator value belongs to dimension and second last will be label.

@daern91 @junajan  Please let me know if it makes sense. Once you guys confirm I can start the development on this.

**Comment by daern91** [comment]
Thanks for digging into this one @VineetKumarKushwaha, I just have one question. What happens if a user wants to import and image URL together with dimensions, but without label?

**Comment by VineetKumarKushwaha** [comment]
@daern91 Then in that case he has to leave label section empty. For my understanding I gave importance to label compare to dimension.

**Comment by daern91** [comment]
Ahh, I see. Sh in that example we would have `http://imageurl || 400x400 ;`?

That solution makes sense to me and should work 👍

**Comment by VineetKumarKushwaha** [comment]
@daern91  Yes you are correct. I will then go ahead and implement it.
